### ISSUE TITLE
Can not use some addons

### ISSUE THREAD

**Issue by johaven** [scttcper/ngx-codemirror#145]
I try to use this addon: https://codemirror.net/demo/loadmode.html

The idea is to put all folder languages in my assets dir, and give formatted url etc ...

How can i access to this variable https://github.com/codemirror/CodeMirror/blob/29e338b8c1f27ade4502839877df7afd49584479/demo/loadmode.html#L65 with ngx-codemirror ?

**Comment by scttcper** [comment]
accessing the editor property

use a viewchild ref to access the component and then its at the public codemirror property https://github.com/TypeCtrl/ngx-codemirror/blob/master/src/lib/codemirror.component.ts#L87

**Comment by johaven** [comment]
Thank you :)

**Comment by johaven** [comment]
Another problem: CodeMirror.autoLoadMode(instance, mode) must be called but `this.codeMirror.codeMirror.autoLoadMode is not a function`

**Comment by johaven** [comment]
I think is related to: https://github.com/codemirror/CodeMirror/issues/5484

**Comment by johaven** [comment]
<img width="383" alt="capture d ecran 2018-11-06 a 18 05 53" src="https://user-images.githubusercontent.com/5459596/48080714-a5819880-e1ee-11e8-8f54-f8d28e61471f.png">

<img width="1119" alt="capture d ecran 2018-11-06 a 18 05 32" src="https://user-images.githubusercontent.com/5459596/48080739-b500e180-e1ee-11e8-9743-cfc78655191d.png">

**Comment by johaven** [comment]
Another information: codemirror from loadmode.js seems to be correctly imported with all functions.

<img width="1356" alt="capture d ecran 2018-11-07 a 21 34 48" src="https://user-images.githubusercontent.com/5459596/48159261-084d5f80-e2d5-11e8-95ad-7f9587704d23.png">

**Comment by johaven** [comment]
This seems to be the case for all the addons

**Comment by johaven** [comment]
After a lot of debugging, it seems _require_ creates a scoped instance of CodeMirror.
Addons have to find a global instance of CodeMirror in plain mode to correctly work.
_fromTextArea_ doesn't return all CodeMirror object (this is why i did not find the addons functions).

My final solution is to mix global instance and this component.
For this i need to declare in angular.json all the scripts to import:

```json
"scripts": [
              "node_modules/codemirror/lib/codemirror.js",
              "node_modules/codemirror/mode/meta.js",
              "node_modules/codemirror/addon/mode/loadmode.js"
            ]
```
If we use _fromTextArea_ from scoped instance, the _setOption_ function will not work.
In ngx-codemirror component replace:
```javascript
declare var require: any; // remove this
const { fromTextArea } = require('codemirror');
this.codeMirror = fromTextArea(this.ref.nativeElement, this._options);
```
by:
```javascript
declare var CodeMirror: any; // replaced by "var require..."
this.codeMirror = CodeMirror.fromTextArea(this.ref.nativeElement, this._options);
```

In my internal component i use _declare  var CodeMirror: any_ to access all functions (ref is the childView of ngx-codemirror component)

```javascript
ngAfterViewInit() {
        CodeMirror.modeURL = this.modeUrl
        const mode = CodeMirror.findModeByFileName(this.file.name).mode // this function is loaded by meta addon
        CodeMirror.autoLoadMode(this.ref.codeMirror, mode) // this function is loaded by loadmode addon
        this.ref.codeMirror.setOption('mode', mode)
    }
```

**Comment by maximelafarie** [comment]
Importing addons like modes as described in the README works perfectly. Here's my `main.ts` file:

```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

// Import your required language in main.ts or at the root of your application
// see https://codemirror.net/mode/index.html
import 'codemirror/mode/javascript/javascript';
import 'codemirror/mode/css/css';
import 'codemirror/mode/htmlmixed/htmlmixed';

import 'codemirror/addon/edit/matchbrackets';
import 'codemirror/addon/edit/closetag';
import 'codemirror/addon/selection/active-line';


if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

and here's my options object to enable the above addons:

```typescript
editorOptions = {
  lineNumbers: true,
  autoCloseTags: true,
  styleActiveLine: true,
  theme: 'monokai',
  mode: 'text/html',
  // define Emmet output profile
  profile: 'xhtml'
};
```

Btw, thank you a lot @scttcper for this awesome ngx wrapper for codemirror! 🙌 
Cheers!

**Comment by johaven** [comment]
This only works for addons that affect the editor (_CodeMirror.fromTextArea_)

**Comment by maximelafarie** [comment]
@johaven I got it! Good to know. 👍

**Comment by maximelafarie** [comment]
Finally I had the same issue as yours but I solved it by doing like that: 

```typescript
import * as CodeMirror from 'codemirror';
```

**Comment by maximelafarie** [comment]
After few research, I try to access [this](https://github.com/TypeCtrl/ngx-codemirror/blob/master/src/lib/codemirror.component.ts#L87) property, I guess it may help... But I can't retrieve it for the moment. 😕

**Comment by scttcper** [comment]
@johaven 	i'm not sure how to fix it for your case. You might try copying out the component and instantiating codemirror as you require, unless there's a way to make it work for everyone's general use.

**Comment by johaven** [comment]
@scttcper This is what i do for the time being.
But if you replace the 2 lines of code, it should work for everyone:
```js
declare var CodeMirror: any; // replaced by "var require..."
this.codeMirror = CodeMirror.fromTextArea(this.ref.nativeElement, this._options);
```
If people want to use other addons like me, they will only have to load the libraries via the Angular scripts tag above, for others it will work the same way.

**Comment by james-powis** [comment]
I am attempting to do something similar except in my case is to dynamically define the mode and load it on the fly based on a matrix of user provided data... @johaven could you provide a StackBlitz showing what you did to get loadmodule fuctional? because I am hitting a brick wall trying to deduce this thread.

**Comment by johaven** [comment]
I do not have much time but I will give you my configuration.

**angular.json**
```js
"scripts": [
              "node_modules/codemirror/lib/codemirror.js",
              "node_modules/codemirror/mode/meta.js",
              "node_modules/codemirror/addon/mode/loadmode.js",
              "node_modules/codemirror/addon/mode/overlay.js"
            ]
```
**codemirror.component.ts diff** I declare this modified component in my module.
<img width="1513" alt="capture d ecran 2019-02-09 a 09 59 25" src="https://user-images.githubusercontent.com/5459596/52518822-75b0b980-2c51-11e9-9687-b99ee26886f0.png">

**Usage example**
```ts
import {AfterViewInit, Component, Input, OnInit, ViewChild, ViewEncapsulation} from '@angular/core'
import {HttpClient} from '@angular/common/http'

declare var CodeMirror: any

@Component({
    selector: 'app-files-viewer-text',
    encapsulation: ViewEncapsulation.None,
    styles: [`
      .CodeMirror {
        height: 100%
      }
    `],
    template: `
      <div [style.height.px]="currentHeight">
        <ngx-codemirror #CodeMirror [(ngModel)]="content" [options]=options></ngx-codemirror>
      </div>`
})
export class FilesViewerTextComponent implements OnInit, AfterViewInit {
    @ViewChild('CodeMirror') ref: any
    @Input() currentHeight: number
    @Input() file: any
    @Input() fileUrl: string
    private readonly modeUrl = '/static/assets/codemirror/mode/%N/%N.js'
    public content: string
    public options: any = {lineNumbers: true, readOnly: true, theme: 'material', mode: 'null'}
    private mode: string = null

    constructor(private http: HttpClient) {
        CodeMirror.modeURL = this.modeUrl
    }

    ngOnInit() {
        const detectedMode = CodeMirror.findModeByFileName(this.file.name)
        if (detectedMode) {
            this.mode = detectedMode.mode
            this.http.get(this.fileUrl, {responseType: 'text'}).subscribe((data: string) => this.content = data)
        } else {
            this.content = 'This file contains binary data that can not be read'
        }
    }

    ngAfterViewInit() {
        if (this.mode) {
            CodeMirror.autoLoadMode(this.ref.codeMirror, this.mode)
            this.ref.codeMirror.setOption('mode', this.mode)
        }
    }
}
```

**Comment by Fillonj** [comment]
Hello, i also had problems to use the mergeView addon, but finally made it, so here is my sample [codemirror-merge-view](https://github.com/Fillonj/codemirror-merge-view)

**Comment by sp90** [comment]
@scttcper this can be closed
