### ISSUE TITLE
editor is not refreshed by [(ngModel)] if editor is unfocused

### ISSUE THREAD

**Issue by amitm02** [scttcper/ngx-codemirror#155]
If the editor is unfocused, the content is not updated if the var under [(ngModel)] has changed.
After clicking the editor, it does update.

**Comment by zaiddabaeen** [comment]
I've got the same issue. Content only shows after clicking on editor. The editor is set to show in a modal so starts unfocused.

Using `[autoFocus]=true` does not solve the issue.

**Comment by conradolk** [comment]
Same issue, the textarea is empty until its focused.

Thanks for the great library.

**Comment by DerekJDev** [comment]
Any update on this?

**Comment by scttcper** [comment]
It sounds like change detection isn't being triggered, how are you changing the variable passed to ngModel

**Comment by rustygreen** [comment]
@DerekJDev can you verify that you have the `FormsModule` imported? This is required in order to use ngModel.

**Comment by ilteoood** [comment]
Same problem here. And yes, FormsModule is imported.
I have this problem only if I put the ngx-codemirror in an *ngFor.

**Comment by onyet** [comment]
after trying several times, and I also tried directly using codemirrorjs to the angular project.
i found that this is caused by the latest version of codemirror.
Solution: downgrade codemirror.  - CMIIW

**Comment by vosuyak** [comment]
Any solution to resolve no content being displayed unless a user clicks on the IDE theme? 

The link below suggests adding the refresh method to the codemirror object.

https://discuss.codemirror.net/t/blank-screen-when-switching-to-another-iframe/1669/2 
@scttcper

**Comment by scttcper** [comment]
ngx-codemirror likely wouldn't know when you want to refresh either in this case. You could access the viewchild and call refresh. If change detection is being fired correctly it should already call refresh.

**Comment by scttcper** [comment]
It updates on focus because there is a state change, meaning your previous updates did not trigger change detection correctly.

**Comment by vosuyak** [comment]
Thanks for the swift response @scttcper .

I should add, the state does not change because the content is the same. In my case and others above, where the hiccup is seen, is when storing the theme in a modal, this results in the need for clicking IDE theme once the modal is open. Other than that it works just fine.

**Comment by scttcper** [comment]
Is the modal being rendered before it is shown?

**Comment by vosuyak** [comment]
Yes it is

**Comment by scttcper** [comment]
Try a `@ViewChild` to force an update after the modal is shown. Would also recommend not rendering the modal until it is needed using angular/cdk

**Comment by vosuyak** [comment]
Hi @scttcper,  I created a small angular 10 app that demonstrates the issue at hand which is. When moving from one tab to another the codemirror is not refreshed forcing the user to click the ide in order to see the content. 

https://github.com/vosuyak/code-editor
Provide feedback when free :)

**Comment by scttcper** [comment]
@vosuyak you might need to push the code

**Comment by vosuyak** [comment]
@scttcper of course, my apologies.  
pushed*

**Comment by scttcper** [comment]
@vosuyak  This is the same pitfall as others, codemirror cannot be rendered offscreen and then shown without being told to re-render.

Use the documented lazy loading https://material.angular.io/components/tabs/overview#lazy-loading

wrap with each tab with `<ng-template matTabContent>`

**Comment by vosuyak** [comment]
@scttcper Sounds like a plan! Thank you!

**Comment by vosuyak** [comment]
@scttcper worked like a charm! pushing those code changes to the main branch. For all other devs watching this issue whose curious about the resolution.
