### ISSUE TITLE
ngx-codemirror doesn't work correctly if model is passed asynchroniously

### ISSUE THREAD

**Issue by kopach** [scttcper/ngx-codemirror#168]
If `ngx-codemirror` is used with `async` pipe - DOM is refreshed infinitly.

For example:
```
            <audit-codemirror
              [ngModel]="model | async"
              [options]="options | async"
            ></audit-codemirror>
```

Something like this will cause DOM refreshing constantly. To see this - open dev tools and inspect codemirror element. This has influence not only on performance but also on rendering: sometimes row nubers are'n shown until textarea is clicked.

**Comment by kopach** [comment]
Hi @scttcper. Could you explain what is the purpose of this function in `ngx-codemirror` component and whether it is still needed: [ngDoCheck](https://github.com/TypeCtrl/ngx-codemirror/blob/master/src/lib/codemirror.component.ts#L120). If I remove this function  from class - everything seems to work as expected with async pipe.

**Comment by scttcper** [comment]
if the options change, the component updates

**Comment by kopach** [comment]
I do use `async` pipe because both `model` and `options` in my case are observables, not just plain objects. I do use ngRx to store all data in one place and once data change - it will asynchronously be populated in all the places of usage.

How about to use `ngOnChanges` hook instead of `ngDoCheck` ? This hook is designed for such cases, I think. Or you have some arguments to do not use it?

**Comment by rdandnayak** [comment]
How about if you try this,
```
<ng-container *ngIf="model | async; let model ">
  <audit-codemirror
              [ngModel]="model | async"
            ></audit-codemirror>
</ng-container>
```

this should work.
