### ISSUE TITLE
Request to change the ViewEncapsulation to None

### ISSUE THREAD

**Issue by alexonaci** [scttcper/ngx-codemirror#200]
Hello, 
It seems like Angular marked as deprecated the ::ng-deep pseudo-class ( https://angular.io/guide/component-styles ) which I use to style the code mirror component. Would it be possible to change the ViewEncapsulation to ViewEncapsulation.None in the component such that we'll be able to add custom styles to the component in the future?

**Comment by scttcper** [comment]
I’ll leave it open if a bunch of people want the same thing, otherwise I think I like it encapsulated

**Comment by zakhenry** [comment]
I agree with @scttcper - angular isn't going to remove emulated view encapsulation until there is a viable alternative
