### ISSUE TITLE
How can you use addons with this wrapper? There's no documentation on that...

### ISSUE THREAD

**Issue by Compgy** [scttcper/ngx-codemirror#280]
I'd like to use a linter addon from codemirror in my Angular project but I can't figure out how it works. Could someone help me with that?

**Comment by lf-novelt** [comment]
just add `import 'codemirror/addon/selection/active-line';` (or whatever official addon, check in the node_modules/codemirror folder to see all available) in your app.module.ts and then pass the appropriate options to the ngx-codemirror componenet
