### ISSUE TITLE
Unable to access CodeMirror.modeInfo property

### ISSUE THREAD

**Issue by polentino** [scttcper/ngx-codemirror#281]
Hi,
I'd like to iterate over `CodeMirror.modeInfo` array in order to populate a _select_ element with all available languages supported by CodeMirror, and let the user choose whatever language fits best for him/her.
The problem is that, at compile time, I got the following error:

`TS2339: Property 'modeInfo' does not exist on type 'typeof CodeMirror'`

even though that variable does exist and is indeed defined (see https://user-images.githubusercontent.com/11738109/90551959-6689c080-e192-11ea-8de1-86cd6b70ea9c.png) 

what I think is happening (but im pretty new to Angular) is that, when I

`import {CodeMirror} from 'codemirror'`;

the compiler looks inside `node_modules/@types/codemirror` directory instead of having a look into `node_modules/codemirror`.

Is there a way to access it? Thanks!

**Comment by scttcper** [comment]
this is how types work

**Comment by polentino** [comment]
and a proposed solution would be?

**Comment by scttcper** [comment]
exit the typescript type system if you suspect it exists on that object or import it another way, its possible its added to a global codemirror object as it isn't seen in https://unpkg.com/codemirror@5.58.3/lib/codemirror.js

**Comment by polentino** [comment]
I'll give it a try, thanks!
