### ISSUE TITLE
Code preview doesnt work in ngFor loop

### ISSUE THREAD

**Issue by slash851** [scttcper/ngx-codemirror#284]
## Description

When placing ngx-codemirror in *ngFor loop I am gettin exception:

`Error: Uncaught (in promise): Error: Cannot assign to a reference or variable!
Error: Cannot assign to a reference or variable!`

### Code used:

```
                       <div *ngFor="let rep of xmlReports;let index = index;">
                               <ngx-codemirror *ngIf="rep" style="height: 700px !important;"
                                name="uniquename{{index}}"
                                id="uniqueid{{index}}"
                                [(ngModel)]="rep"
                                [options]="{
                                              lineNumbers: 100,
                                              theme: 'default',
                                              mode: 'xml'
                                            }"
                        ></ngx-codemirror>
                     </div>
```

where xmlReports is an array of strings 

## Current behaviour
when in loop its throwing exception
when removing loop and using first element of that arrya - it works

## Expected behaviour 
allowing looping through the array of string
should display number of ngx-codemirror elements

## Environment
Angular 6.x.x
ngx-codemirror version: 1.3.10
os: Ubuntu
browser: Chrome Latest (other browsers same issue)

--

**Comment by polentino** [comment]
maybe this quick trick should help you https://github.com/scttcper/ngx-codemirror/issues/168#issuecomment-567424848

**Comment by scttcper** [comment]
This works as expected in the latest verison.

```
<div class="ngx-codemirror mb-2" *ngFor="let x of ['1','2','3']">
  <ngx-codemirror
    [options]="options"
    [ngModel]="x"
    [disabled]="readOnly"
    [autoFocus]="true"
    (ngModelChange)="handleChange($event)"
  ></ngx-codemirror>
</div>
```
