### ISSUE TITLE
Code Folding in gherkin mode does not work. Is it even supported ?

### ISSUE THREAD

**Issue by NabaragRebaca** [scttcper/ngx-codemirror#294]
I have a web editor which is in gherkin mode and I need to add support of code folding. In ngx-codemirror there's an option called foldGutter and I have made it true in the option. Also set "CodeMirror-foldgutter" in "gutters" option.

here is the component -

```
<ngx-codemirror #codemirrorr
[options]="{
 lineNumbers: true,
 theme: 'idea',
 mode: 'gherkin',
 gutters: ['CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
 foldGutter: true    
}"
[(ngModel)]="dataSet"
(ngModelChange)="setData($event)">
</ngx-codemirror>
```

Imported following addon js
```
import 'codemirror/lib/codemirror';
import 'codemirror/mode/gherkin/gherkin';
import 'codemirror/addon/fold/comment-fold';
import 'codemirror/addon/fold/markdown-fold';
import 'codemirror/addon/fold/foldgutter';
import 'codemirror/addon/fold/brace-fold';
import 'codemirror/addon/fold/foldcode';
import 'codemirror/addon/fold/indent-fold';
```

Also in my styles.scss i have imported following css

`@import '~codemirror/addon/fold/foldgutter.css';`

But the code folding option is not coming up in the editor.  Or does codemirror even support code folding on gherkin mode or its only available for JS, HTML, Python and XML?

**Comment by scttcper** [comment]
not sure
