### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by eriky** [scttcper/ngx-codemirror#300]
When I build my project, that depends on `ngx-codemirror`, I get the following warning from Angular:

`Warning: app.module.ts depends on '@ctrl/ngx-codemirror'. CommonJS or AMD dependencies can cause optimization bailouts.`

For more info, see https://angular.io/guide/build#configuring-commonjs-dependencies

Quoting from that page:

    Depending on CommonJS modules can prevent bundlers and minifiers
    from optimizing your application, which results in larger bundle sizes. 
    Instead, it is recommended that you use ECMAScript modules in your entire application. 

This happens using Angular 11.2.13. I'm not sure how much of a problem this really is, but I wanted to put this out here just in 
    case nobody encountered it yet.

**Comment by scttcper** [comment]
the current version of codemirror is commonjs
