### ISSUE TITLE
v5.1.0 has breaking changes - ERROR ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Clashsoft** [scttcper/ngx-codemirror#304]
I accidentally updated to v5.1.0 and it does not work with Angular 12.

```
ERROR ReferenceError: require is not defined
    at e.get codeMirrorGlobal [as codeMirrorGlobal] (main-es2017.288b33d35bec7fd4a44d.js:1)
    ...
```

Downgrading to v5.0.1 fixed it.

**Comment by datalowe** [comment]
I get the exact same error, on Angular v12.2.4 when using the development server (haven't tried other situations) and only once I activate/show a component which wraps the code mirror component. When using v5.0.1 of ngx-codemirror as @Clashsoft suggested, everything works as expected.

**Comment by scttcper** [comment]
5.1.1 might have fixed it, not sure https://github.com/scttcper/ngx-codemirror/releases/tag/v5.1.1

**Comment by stirelli** [comment]
Yes, indeed. 5.1.1 fixes the error. Thanks @scttcper

**Comment by Clashsoft** [comment]
This should be documented in the Readme
