### ISSUE TITLE
Problem getting CodeMirror instance with Angular 13

### ISSUE THREAD

**Issue by foorschtbar** [scttcper/ngx-codemirror#310]
Hi,

i can't get access to the CodeMirror instance with Angular 13. Unfortunately, I'm stuck and can't find the error. I have looked at these posts and also tried - unfortunately without success

- https://github.com/scttcper/ngx-codemirror/issues/289#issuecomment-716099968
- https://github.com/scttcper/ngx-codemirror/issues/191#issuecomment-508228492
- https://github.com/scttcper/ngx-codemirror/issues/146
- https://github.com/scttcper/ngx-codemirror/issues/109
- https://stackoverflow.com/a/51942700

My code to get the instance is:

`app.component.html`
```html
<ngx-codemirror #codeMirror [...]></ngx-codemirror>
```

`app.component.ts`
```javascript
import { CodemirrorComponent } from '@ctrl/ngx-codemirror';
[...]
@ViewChild('codeMirror') codeMirrorCmpt: CodemirrorComponent;
[...]
 ngAfterViewInit() {
    console.log("this.codeMirrorCmpt", this.codeMirrorCmpt);
    console.log("this.codeMirrorCmpt.codeMirror", this.codeMirrorCmpt.codeMirror); // --> undefined
  }
```

I always get `undefined` for `this.codeMirrorCmpt.codeMirror`, although the `this.codeMirrorCmpt`object had a codeMirror-Node.

![](https://user-images.githubusercontent.com/10727275/171630277-81f6f65d-d43f-4eae-97f2-236b3b461728.png)

Here is also a MWE: https://stackblitz.com/edit/angular-ivy-6byrzp

Regards,
Fabian

**Comment by wuboy0307** [comment]
I met the same problem. But if I move the line to a function which will call later. It works.

```
  ngAfterViewInit() {
    this.changeDetectorRef.detectChanges();
  }

  validateFormula(e) {
    this.codeMirrorEditor = this.editor.codeMirror;  // here
  }
```

**Comment by foorschtbar** [comment]
Thank u @wuboy0307! The *later* was the key:

```ts
const timer = setInterval(() => {
  if (this.codeMirrorCmpt.codeMirror !== undefined) {
    console.log("now working!", this.codeMirrorCmpt.codeMirror)
    [...]
    clearInterval(timer);
  } else {
    console.log("nope :(")
  }
}, 500)
```
