### ISSUE TITLE
Help: multiple editor on same screen have same state.

### ISSUE THREAD

**Issue by dev-arminder** [scttcper/ngx-codemirror#316]
Hi I am trying to use two differen editor on same URL ( same route). I had given them different ref and name. 
e.g
![image](https://user-images.githubusercontent.com/85746323/211246637-29009c93-74a6-4458-88be-eea1518a6cb9.png)
![image](https://user-images.githubusercontent.com/85746323/211246660-4e32b309-e76b-41e8-ac39-3a087a8920c2.png)

From TS File 
![image](https://user-images.githubusercontent.com/85746323/211246697-b80374c0-d9af-44b5-b84c-82580b746add.png)
Whenever I am trying to setValue of one element other get updated automatically. I want two different values for them. 

Angular  Version - 12
ngx-codemirror version - 5.1.1

**Comment by lgpage** [comment]
Hi @dev-arminder 

It looks like your `ngx-codemirror` components are binding to the same model property `obj`.
Try using different model properties, one for the first `ngx-codemirror` component and another for the second `ngx-codemirror` component.

**Comment by dev-arminder** [comment]
Oh Yeah @lgpage It works, but earlier I thinking to initialize with same value, updated value coming from API. I think i misunderstood `[(ngModel)]`. Btw thanks a lot @lgpage 👍
